CREATE PROCEDURE [dbo].[spStudent_DeleteAll]
AS
BEGIN TRY
    BEGIN TRANSACTION
		UPDATE dbo.[Student]
		SET Archived = 1
		WHERE Archived = 0
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION
END CATCH